# Generated by Django 6.0.3 on 2026-05-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0003_author_publisher_booklab9'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklab9',
            name='pubdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
